<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< Updated upstream
<<<<<<< HEAD
<testsuite ignored="0" hostname="DESKTOP-9K20K49" failures="4" tests="4" name="Default test" time="63.367" errors="0" timestamp="2021-04-28T17:52:04 ICT">
  <testcase classname="poro.module.db.data.PhongTest" name="InsertPhong" time="15.94">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.sql.Connection.prepareStatement(String)&amp;quot; because the return value of &amp;quot;poro.module.db.DatabaseManager.openConnect()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because the return value of "poro.module.db.DatabaseManager.openConnect()" is null
at poro.module.db.DatabaseManager.getPreStm(DatabaseManager.java:59)
at poro.module.db.DatabaseManager.executeUpdate(DatabaseManager.java:100)
at poro.module.db.data.PhongTest.InsertPhong(PhongTest.java:38)
=======
<testsuite ignored="5" hostname="Neko" failures="1" tests="1" name="Default test" time="0.998" errors="0" timestamp="2021-04-28T03:05:59 ICT">
  <testcase classname="poro.module.db.data.MuonPhongTest" name="getListByPhongYesTest" time="0.932">
    <failure type="java.lang.AssertionError" message="Khi lấy list thông tin mượn phòng 101, kết quả trả về là list rổng expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Khi lấy list thông tin mượn phòng 101, kết quả trả về là list rổng expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at poro.module.db.data.MuonPhongTest.getListByPhongYesTest(MuonPhongTest.java:24)
>>>>>>> 6ce5c585cc76950cf7fb3468ffc2154e3f39c068
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
<<<<<<< HEAD
  </testcase> <!-- InsertPhong -->
  <testcase classname="poro.module.db.data.PhongTest" name="SelectAllphong" time="15.786">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.sql.Connection.prepareCall(String)&amp;quot; because the return value of &amp;quot;poro.module.db.DatabaseManager.openConnect()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareCall(String)" because the return value of "poro.module.db.DatabaseManager.openConnect()" is null
at poro.module.db.DatabaseManager.getPreStm(DatabaseManager.java:57)
at poro.module.db.DatabaseManager.executeQuery(DatabaseManager.java:78)
at poro.module.db.data.PhongTest.SelectAllphong(PhongTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SelectAllphong -->
  <testcase classname="poro.module.db.data.PhongTest" name="SelectByIdPhong" time="15.794">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.sql.Connection.prepareCall(String)&amp;quot; because the return value of &amp;quot;poro.module.db.DatabaseManager.openConnect()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareCall(String)" because the return value of "poro.module.db.DatabaseManager.openConnect()" is null
at poro.module.db.DatabaseManager.getPreStm(DatabaseManager.java:57)
at poro.module.db.DatabaseManager.executeQuery(DatabaseManager.java:78)
at poro.module.db.data.PhongTest.SelectByIdPhong(PhongTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SelectByIdPhong -->
  <testcase classname="poro.module.db.data.PhongTest" name="UpdatePhong" time="15.797">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.sql.Connection.prepareStatement(String)&amp;quot; because the return value of &amp;quot;poro.module.db.DatabaseManager.openConnect()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because the return value of "poro.module.db.DatabaseManager.openConnect()" is null
at poro.module.db.DatabaseManager.getPreStm(DatabaseManager.java:59)
at poro.module.db.DatabaseManager.executeUpdate(DatabaseManager.java:100)
at poro.module.db.data.PhongTest.UpdatePhong(PhongTest.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- UpdatePhong -->
=======
  </testcase> <!-- getListByPhongYesTest -->
  <testcase classname="poro.module.db.data.MuonPhongTest" name="getFullListTest" time="0.0">
=======
<testsuite ignored="5" hostname="Neko" failures="0" tests="1" name="Default test" time="0.442" errors="0" timestamp="2021-04-28T18:41:09 ICT">
  <testcase classname="poro.module.CalendarManagerTest" name="getDateByStringTest" time="0.35"/>
  <testcase classname="poro.module.CalendarManagerTest" name="getStringTest" time="0.0">
>>>>>>> Stashed changes
    <ignored/>
  </testcase> <!-- getStringTest -->
  <testcase classname="poro.module.CalendarManagerTest" name="addTimesTest" time="0.0">
    <ignored/>
  </testcase> <!-- addTimesTest -->
  <testcase classname="poro.module.CalendarManagerTest" name="getDaysOfTest" time="0.0">
    <ignored/>
  </testcase> <!-- getDaysOfTest -->
  <testcase classname="poro.module.CalendarManagerTest" name="isLeapYearTest" time="0.0">
    <ignored/>
  </testcase> <!-- isLeapYearTest -->
  <testcase classname="poro.module.CalendarManagerTest" name="getNowTest" time="0.0">
    <ignored/>
<<<<<<< Updated upstream
  </testcase> <!-- seleteLastMuonPhongTest -->
>>>>>>> 6ce5c585cc76950cf7fb3468ffc2154e3f39c068
=======
  </testcase> <!-- getNowTest -->
>>>>>>> Stashed changes
</testsuite> <!-- Default test -->
