<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="Neko" failures="1" tests="1" name="Default test" time="0.998" errors="0" timestamp="2021-04-28T03:05:59 ICT">
  <testcase classname="poro.module.db.data.MuonPhongTest" name="getListByPhongYesTest" time="0.932">
    <failure type="java.lang.AssertionError" message="Khi lấy list thông tin mượn phòng 101, kết quả trả về là list rổng expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Khi lấy list thông tin mượn phòng 101, kết quả trả về là list rổng expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at poro.module.db.data.MuonPhongTest.getListByPhongYesTest(MuonPhongTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getListByPhongYesTest -->
  <testcase classname="poro.module.db.data.MuonPhongTest" name="getFullListTest" time="0.0">
    <ignored/>
  </testcase> <!-- getFullListTest -->
  <testcase classname="poro.module.db.data.MuonPhongTest" name="updateMuonPhongTest" time="0.0">
    <ignored/>
  </testcase> <!-- updateMuonPhongTest -->
  <testcase classname="poro.module.db.data.MuonPhongTest" name="insertMuonPhongTest" time="0.0">
    <ignored/>
  </testcase> <!-- insertMuonPhongTest -->
  <testcase classname="poro.module.db.data.MuonPhongTest" name="getListByPhongNoTest" time="0.0">
    <ignored/>
  </testcase> <!-- getListByPhongNoTest -->
  <testcase classname="poro.module.db.data.MuonPhongTest" name="seleteLastMuonPhongTest" time="0.0">
    <ignored/>
  </testcase> <!-- seleteLastMuonPhongTest -->
</testsuite> <!-- Default test -->
