<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Neko" failures="1" tests="13" name="poro.gui.QuanLyPhongJPanelTest" time="88.504" errors="2" timestamp="2021-04-28T21:15:39 ICT" skipped="0">
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="ThemPhong" time="9.282"/>
  <system-out/>
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="ThemPhong" time="5.890"/>
  <system-out/>
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="ThemPhong" time="5.961"/>
  <system-out/>
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="ThemPhong" time="6.293"/>
  <system-out/>
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="ThemPhong" time="4.821">
    <error message="Cannot invoke &quot;javax.swing.JDialog.getTitle()&quot; because &quot;jp&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "javax.swing.JDialog.getTitle()" because "jp" is null
at poro.gui.QuanLyPhongJPanelTest.ThemPhong(QuanLyPhongJPanelTest.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </error>
  </testcase> <!-- ThemPhong -->
  <system-out/>
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="ThemPhong" time="5.724"/>
  <system-out/>
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="SuaPhong" time="7.835"/>
  <system-out/>
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="SuaPhong" time="8.177"/>
  <system-out/>
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="SuaPhong" time="8.275"/>
  <system-out/>
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="SuaPhong" time="7.700">
    <failure message="expected [] but found [qưe]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [] but found [qưe]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at poro.gui.QuanLyPhongJPanelTest.SuaPhong(QuanLyPhongJPanelTest.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- SuaPhong -->
  <system-out/>
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="XoaPhong" time="7.818"/>
  <system-out/>
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="XoaPhongNhap" time="2.699">
    <error message="Row index out of range" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Row index out of range
at java.desktop/javax.swing.JTable.boundRow(JTable.java:2150)
at java.desktop/javax.swing.JTable.setRowSelectionInterval(JTable.java:2173)
at poro.gui.QuanLyPhongJPanelTest.XoaPhongNhap(QuanLyPhongJPanelTest.java:178)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </error>
  </testcase> <!-- XoaPhongNhap -->
  <system-out/>
  <testcase classname="poro.gui.QuanLyPhongJPanelTest" name="XoaPhongNhap" time="8.029"/>
  <system-out/>
</testsuite> <!-- poro.gui.QuanLyPhongJPanelTest -->
